### ISSUE TITLE
APK link is not working.

### ISSUE THREAD

**Issue by babai93** [sauravpradhan/AndroidGPXRecorder#1]
APK link is not working.

**Comment by sauravpradhan** [comment]
@babai93 Which version of Os you are trying on ? May be permissions ? Pls let me know what is not working ?

**Comment by babai93** [comment]
The APK Download link is not working...
https://drive.google.com/file/d/0Byaspar4S5SEcURJZWhfMnpqQUE/view

**Comment by sauravpradhan** [comment]
Pls find the updated link: https://drive.google.com/file/d/1Kr8w2FR678bXWEr_WJ4M14zGHX52EO3q/view?usp=sharing
